### ISSUE TITLE
A issue of MMK's correction of var(s) 

### ISSUE THREAD

**Issue by fish-galaxy** [mmhs013/pyMannKendall#16]
In the size of 'accout for autocorrelation', i have no ideal of sni's calculation,  the sni just involve the signicant cor, is that true?

**Comment by mmhs013** [comment]
@fish-galaxy, Yes, kind of. If there is significate autocorrelation up to **lag**, then it calculates **sni**,  which used for variance correction according to _Hamed and Rao (1998)_ method. Please check **Hamed and Rao (1998)** paper for details.
