### ISSUE TITLE
np.nanmedian issue in newer versions of numpy...

### ISSUE THREAD

**Issue by mariusz-pelc** [mmhs013/pyMannKendall#17]
Hi,

I have tried to use this module and there was a problem in newer versions of numpy >1.9.0 there is no np.nanmedian() function hence I could not get it working until I changed the np.nanmedian() calls to np.median(). However, before doing that, just after the _preprcessing(x) function I have removed the NaN values from x to make the np.median() work:
    x, c = __preprocessing(x)
    x = x[np.isfinite(x)]
After a few tests it seems to be fine...

Best
M.

**Comment by mmhs013** [comment]
@mariusz-pelc, thanks for your recommendation. I will check it and fix this issue in the next update.
