### ISSUE TITLE
How to indicate the region in the Regional MK test?

### ISSUE THREAD

**Issue by rafael-chgs** [mmhs013/pyMannKendall#18]
I've read different explanations of the Regional Mann Kendall test, and for what I understand it's necessary to declare the location of each time series at least so to lump the S statistic together, just like with Seasonal there's an indication of the frequency of the season. I've seen that in the package the Regional MK test only has the data input. How does it work? I've read the READme, the examples and I can't figure it out. Thanks!

**Comment by mmhs013** [comment]
@rafael-chgs, thanks for your query. Actually, I have planned to write a details guide for this package but can not manage time to complete it.
In mk.regional_test, you need to pass a 2D array, where every column represents the different location/station data. Here is an example

```python
import numpy as np
import pymannkendall as mk

# generate random data
x = np.random.rand(1000,5)   # here consider 5 station/location where every station have 1000 data
trend,h,p,z,tau,s,var_s,slope,intercept = mk.regional_test(x, 0.05)
```
