### ISSUE TITLE
[JOSS review] A statement of need

### ISSUE THREAD

**Issue by rreinecke** [mmhs013/pyMannKendall#2]
Please state for what the software can be used more clearly in the project description. Maybe even include a plot of an example time-series.

**Comment by rreinecke** [comment]
@mmhs013 Really nice! Can you link the example in the main REDME so that interested user can easily find it?

**Comment by mmhs013** [comment]
@rreinecke I am already link it in Usage section of main readme file.

**Comment by rreinecke** [comment]
@mmhs013 All right I'm closing this issues. I would still recommend to you to copy one example figure to the readme to make it more attractive for possible users and the link a little more prominent.
