### ISSUE TITLE
Elaboration on output tuple parameters

### ISSUE THREAD

**Issue by sachinkrane** [mmhs013/pyMannKendall#22]
Can the tuple parameters (viz. z, tau, s, var_s, slope, intercept) be elaborated in more detail?

It's not quite clear what exactly these are representing w.r.t. the algorithm outputs such that it could help one to justify mathematically the results.

Thanks.

**Comment by mmhs013** [comment]
@sachinkrane, the outputs are based on those statistical tests. Please read the _Reference Papers_ for a clear understanding. You need to have a clear understanding of the MK test before using this package.
