### ISSUE TITLE
Is there any workaround for the 'ZeroDivisionError: float division by zero' when using original test ?

### ISSUE THREAD

**Issue by AniIlyich** [mmhs013/pyMannKendall#26]
Hi there,
I was trying to find trend of precipitartion datasets of gpcc and  encountered the error 'ZeroDivisionError: float division by zero'. 
Is there a way to avoid these errors ?
thanks!

![Screenshot from 2022-11-14 12-32-58](https://user-images.githubusercontent.com/112694603/201595780-70b0c1e3-9ca2-476f-b343-63b86f4ead9c.png)

**Comment by NousMei** [comment]
The same issue

**Comment by mmhs013** [comment]
@AniIlyich, @NousMei, 
When your Number of data is n=1 or 0, then `(0.5*n*(n-1))` becomes 0. So, in line 253, `s/(0.5*n*(n-1))` become `s/0`. But, you can't divide any number by 0. So this error shows up.

So, please use minimum 2 data to use `pymannkendall` test.

N.B. According to Statistics, you need a minimum of 30 data points for any type of statistical test.
