### ISSUE TITLE
pyMannKendall not compatible with numpy 1.24.0

### ISSUE THREAD

**Issue by tschager** [mmhs013/pyMannKendall#27]
The latest release of pyMannKendall is not compatible to numpy 1.24.0 due to deprecation of `np.float` ([Numpy v1.24.0 Changelog](https://numpy.org/doc/stable/release/1.24.0-notes.html). 
There is already a fix in the master branch [commit](https://github.com/mmhs013/pyMannKendall/commit/9c149850f76e04749eadd82c78ed72c4604c1f6c), so a new release of pyMannKendall would fix this issue.

**Comment by CrispyCrafter** [comment]
For the time being this might be a sufficient workaround:
`pip install git+https://github.com/mmhs013/pyMannKendall.git@master `

**Comment by mmhs013** [comment]
@tschager, thanks for your comments. Today I have released version 1.4.3 to fix this issue.
