### ISSUE TITLE
Version needs to be updated/match in all locations

### ISSUE THREAD

**Issue by dhhagan** [mmhs013/pyMannKendall#7]
It looks like the version [here](https://github.com/mmhs013/pyMannKendall/blob/master/pymannkendall/__init__.py#L3) doesn't match with what is listed for review or in the setup.py file. Should be a simple update, though you may want to talk a look at a [versioneer](https://github.com/warner/python-versioneer) which does all the hard work for you!

**Comment by mmhs013** [comment]
@dhhagan Thank you for highlighting over the matter. It just skipped my eyes. I already fix it.

Thanks for your suggestion. I just checked `versioneer`. As soon as possible I will try to incorporate this in my project.

**Comment by mmhs013** [comment]
@dhhagan I already implement versioneer in my project.
